.github/workflows/cargo_test.yml, Cargo.lock, Cargo.toml, src/app/bmc_application.rs, src/c_interface.rs, src/middleware/event_listener.rs, src/middleware/gpio_definitions.rs, src/middleware/helpers.rs, src/middleware/mod.rs, src/middleware/pin_controller.rs, src/middleware/power_controller.rs
Rework that was done during debugging of #49. Mainly moved around code + small changes. 
* Cut off power-related logic from pin_controller into a power_controller.
* Did an attempt to clean up the USB-controlling interface. @ruslashev could you double check this? see `bmc_application.rs:229`
This commit cannot be used with the new Device tree of #49. My hypnosis is that there is an issue with the gpio aggregator, or buffered file writes, so for now i commit the user space changes that work on the current device tree.
=> Gh-10 rework pin controller

Cargo.lock, Cargo.toml, src/app/bmc_application.rs, src/middleware/firmware_update_usb.rs, src/middleware/mod.rs, src/middleware/rk1_fwudate.rs, src/middleware/rpi_fwupdate.rs, src/middleware/usbboot.rs
This task it the first in the sequence that provides the flashing feature for RK1 compute modules. In this commit raspberry specific code is moved to a seperate file. Secondly the runway is implemented to support multiple "drivers" that enable read/write to internal storage of compute modules. e.g. Writing new firmware to eMMC storage of a module
* the firmware upgrade code for raspberry pi moved from `bmc_application.rs` to `rpi_fwupdate.rs`
see:
https://github.com/turing-machines/BMC-Firmware/issues/45
=> GH-45 extract raspberry specific to seperate module

src/middleware/pin_controller.rs
Due to a specification + implementation mishap, values for a USB-A power-controlling pin were inverted, leading to port being disabled when the opposite was expected. In the future, this should be caught by a special test runner.
Fixes #15
=> pin_controller: fix wrong USB_PWEN values breaking USB host mode

src/middleware/firmware_update/transport.rs, src/middleware/usbboot.rs
Secondly, the `calc_file_checksum` function is hiding the error Result in case of an error respones. Made it early return instead on Error.
=> StdTransportWrapper: fix buffer copy

Cargo.lock, Cargo.toml, bmcd/Cargo.toml, bmcd/src/flash_service.rs, bmcd/src/into_legacy_response.rs, bmcd/src/legacy.rs, bmcd/src/main.rs, tpi_rs/Cargo.toml, tpi_rs/src/app/flash_application.rs, tpi_rs/src/c_interface.rs, tpi_rs/src/utils/io.rs, tpi_rs/src/utils/mod.rs
Added a handler in the 'bmcd' that:
* receives a firmware image over the http API endpoint
* buffers these image chunks
* async write chunks to a given node
=> flash_service: implement file streaming handler

bmcd/src/main.rs
Prevent the TCP connection from closing during a flashing process. When the receive buffer is full, byte chunk requests will be blocked until new space becomes available. This caused connection resets, resulting in an abort of the flashing process. This happens, for example, during the configuration phase of the node which typically takes longer as 5 sec. default keep-alive for HTTP1.1 was 5 sec. This CL align sets the keep-alive timeout to the value of the underlaying OS.
=> bmcd: listen on IPv6 & increase KeepAlive

Cargo.lock, Cargo.toml, bmcd/Cargo.toml, bmcd/src/config.rs, bmcd/src/main.rs
TLS is added and enforced. the bmcd requires a `--certificate` and `--private-key` argument in order to run.
A server is binded onto the old `80` port, that will redirect traffic to 443
=> enable tls

bmcd/src/legacy.rs, tpi_rs/src/app/bmc_application.rs, tpi_rs/src/app/flash_application.rs, tpi_rs/src/c_interface.rs
* split the usbboot pin functionality from the usb configuration and gave it its separate routine call.
* usb_boot pin is now exposed over the API via opt=set&type=usb_boot
=> added "usb_boot" operation

Cargo.lock, bmcd/Cargo.toml, bmcd/src/config.rs, bmcd/src/main.rs, default_config.yaml, deny.toml, tpi_rs/src/app/bmc_application.rs, tpi_rs/src/c_interface.rs, tpi_rs/src/middleware/persistency/app_persistency.rs, tpi_rs/src/middleware/persistency/binary_persistency.rs, tpi_rs/src/middleware/persistency/error.rs, tpi_rs/src/utils/ring_buf.rs
* Implemented a fallback mechanism when the database binary is corrupted. In this case the binary will be omitted and overwritten with an default store on successive write-backs of the store to disk
* Improved fatal error messages on erroneous `.get()` and `.set()` calls.
* Created a new config file item: `write_timeout`. Controls the write timeout of the persistency. More information inside `default_config.yaml`
=> persistency: maturing component

src/api/legacy.rs, src/api/streaming_data_service.rs, src/app/bmc_application.rs, src/app/firmware_runner.rs, src/firmware_update/mod.rs, src/firmware_update/rockusb_fwudate.rs, src/firmware_update/rpi_fwupdate.rs, src/firmware_update/transport.rs, src/hal/usbboot.rs, src/utils/mod.rs
* Use the "new" rockusb driver instead of the `rockusb` rs implementation.
* Cleaned up the async logging/state component. Error information should flow back via "FwUdateError".
=> firmware_update: rockusb_fwudate

src/authentication/authentication_context.rs, src/authentication/authentication_service.rs
This causes browsers to ask and use authentication credentials
Fixes turing-machines/BMC-Firmware#127
=> auth: ask for `Basic` authentication scheme

src/authentication/authentication_context.rs, src/authentication/authentication_errors.rs, src/authentication/authentication_service.rs, src/authentication/linux_authenticator.rs, src/main.rs
When responding with an unauthorized response, make sure that the correct header is returned based on the scheme used.
Only a "realm" attribute is used when the scheme is unknown or not parse-able.
=> auth: format authorization denied based on scheme

src/api/legacy.rs, src/api/streaming_data_service.rs
When the channel closes which the sender uses to transport the file data. Ask the `StreamingDataService` what the current error state is rather then just responding to the client with a generic answer.
=> streaming_data_service: improve error message

src/firmware_update/rpi_fwupdate.rs, src/hal/stub/usbboot.rs, src/hal/usbboot.rs
After turing-machines/BMC-Firmware@1193ce32 mdev replaced eudev, and with it directory of symlinks /dev/disk/by-id stopped being generated. Work around this by searching in /sys/block instead.
=> usbboot: move searching from `/dev/disk/by-id` to `/sys/block`

src/api/streaming_data_service.rs, src/app/bmc_application.rs, src/app/firmware_runner.rs, src/main.rs
This commit contains 2 improvements:
* Internal operations are not triggering persistency updates anymore. Minimizing flash wear.
* After a flash command the power and USB settings are restored to their previous values
=> bmc_application: restore power and usb settings

src/api/legacy.rs, src/app.rs, src/app/bmc_info.rs
Exposes 2 additional endpoints in the API. Intended to serve the BMC-UI. It sorts version related strings in a 'about' call and info about your specific board into 'info'
=> expose additional endpoint

src/api/legacy.rs, src/app/bmc_application.rs, src/hal.rs, src/utils.rs
For testing, use
curl 'https://turingpi.local/api/bmc?opt=set&type=node_info' \
-X POST \
-H "Content-Type: application/json" \
-d '
{
"node_info":
[
{
"node": 1,
"module_name": "Raspberry Pi CM4",
"uart_baud": 115200
},
{
"node": 3,
"name": "New Name"
}
]
}' \
-k \
--header "Authorization: Bearer $token"
Closes #77
=> api: add `node_info` set & get endpoints

src/main.rs
This issue is fixed in v2: https://github.com/turing-machines/BMC-Firmware/issues/79
But please open port 80 and 443 on IPv6 too, so that its fully working on IPv6 only networks.
=> open port 80+443 on ipv6 too

src/api/legacy.rs, src/app.rs, src/app/cooling_device.rs
Adds logic around the `/sys/class/thermal` devices, listing all found records as a JSON array for `get_cooling_state` and `set_cooling_state` to set a new speed for a specific device.
The two added endpoints and their respective responses are:
```
https://turingpi.local/api/bmc?opt=get&type=cooling
{
"response": [
{
"result": [
{
"device": "cooling_device0",
"max_speed": 10,
"speed": 0
}
]
}
]
}
```
```
https://turingpi.local/api/bmc?opt=set&type=cooling&device=cooling_device0&speed=5
{
"response": [
{
"result": "ok"
}
]
}
```
I built a working firmware [here](https://github.com/barrenechea/BMC-Firmware/actions/runs/8591403659) to get that output from my own v2.4 board.
The logic I wrote technically supports more than one fan if the hardware allows it. I expect this to be limited to a …
=> feat: add API support for cooling devices

default_config.yaml, src/main.rs
Since the local `tpi` utility appears to rely on the `bmcd`, it can't be disabled, but I'm racking up a TuringPi2 at the datacenter shortly, so the BMC will have a public IP address and I would like to avoid exposing the HTTP server to the world.
=> Allow binding to a configurable address.

src/main.rs
The changes are:
- Removed Basic Auth for static files, allowing the SpA to handle authentication & routes protection. Addressed by fce2d93d01a3b452e9cab2b1f8bc192aab6fb6c0
- Allow SpA to resolve routes. cfaae9c9988f35a7d083809effde5c4140cc0a8a
Aims to provide support for https://github.com/turing-machines/BMC-UI/pull/5
=> Removes Basic Auth for static files, enables SpA route handling
